### ISSUE TITLE
Uncaught Error: Error: Command failed: C:\Users\kot\AppData\Roaming\cabal\bin\ghc-mod.exe check C:\Users\KIRICH~1.KL\AppData\Local\Temp\haskell-ghc-mod11539-4120-1xwonak.hsuser error (ghc not found)

### ISSUE THREAD

**Issue by vasily-kirichenko** [lierdakil/haskell-ghc-mod#10]
From command line (OK):
```
ghc-mod check src\Main.hs
src\Main.hs:5:1:parse error (possibly incorrect indentation or mismatched brackets)
```
In Atom:

**Atom Version**: 0.189.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.4.3

### Stack Trace

Uncaught Error: Error: Command failed: C:\Users\kot\AppData\Roaming\cabal\bin\ghc-mod.exe check C:\Users\kot\AppData\Local\Temp\haskell-ghc-mod11539-4120-1xwonak.hs
user error (ghc not found)

```
At C:\Users\kot\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:70

Error: Error: Command failed: C:\Users\kot\AppData\Roaming\cabal\bin\ghc-mod.exe check C:\Users\kot\AppData\Local\Temp\haskell-ghc-mod11539-4120-1xwonak.hs
user error (ghc not found)

  at C:\Users\kot\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:70:17
  at ChildProcess.exithandler (child_process.js:736:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1070:5)

```

### Commands

```
     -3:30.6 core:confirm (atom-text-editor.editor.mini)
     -1:41.7 core:save (atom-text-editor.editor.is-focused)
     -0:26.5 core:paste (atom-text-editor#haskell-ghc-mod.ghcModiPath.editor.mini)
     -0:18.5 core:copy (atom-text-editor#haskell-ghc-mod.ghcModiPath.editor.mini)
     -0:17.3 core:paste (atom-text-editor#haskell-ghc-mod.ghcModPath.editor.mini)
  5x -0:16.4 core:move-left (atom-text-editor#haskell-ghc-mod.ghcModPath.editor.mini)
     -0:15.5 core:delete (atom-text-editor#haskell-ghc-mod.ghcModPath.editor.mini)
     -0:08.5 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "audioBeep": false
  },
  "haskell-ghc-mod": {
    "ghcModiPath": "C:\\Users\\kot\\AppData\\Roaming\\cabal\\bin\\ghc-modi.exe",
    "ghcModPath": "C:\\Users\\kot\\AppData\\Roaming\\cabal\\bin\\ghc-mod.exe"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.2.1
autocomplete-plus, v2.7.1
haskell-ghc-mod, v0.4.3
language-haskell, v1.0.0
language-rust, v0.4.2
linter, v0.12.0
linter-rust, v0.0.8
racer, v0.9.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Sorry, no idea. I can only guess that ghc is somehow not in system PATH.

**Comment by vasily-kirichenko** [comment]
I restarted atom and everything is ok now. Sorry.
