### ISSUE TITLE
Check after save failed: hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by itkovian** [lierdakil/haskell-ghc-mod#6]
[Enter steps to reproduce below:]

1. cabal configure
2. cabal build
3. save a file in the project

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.4.3

### Stack Trace

Uncaught Error: Error: Command failed: /Users/ageorges/Library/Haskell/bin/ghc-mod check /var/folders/td/j6b6fl5s2jgbmdb1vvsqzj3m0000gn/T/haskell-ghc-mod115217-31189-1lyb7xt.hs
ghc-mod: /Users/ageorges/tmp/hs-admin/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)

```
At /Users/ageorges/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:70

Error: Error: Command failed: /Users/ageorges/Library/Haskell/bin/ghc-mod check /var/folders/td/j6b6fl5s2jgbmdb1vvsqzj3m0000gn/T/haskell-ghc-mod115217-31189-1lyb7xt.hs
ghc-mod: /Users/ageorges/tmp/hs-admin/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)

  at /Users/ageorges/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:70:17
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  5x -0:10.1 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:09.3 core:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:08.5 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  4x -0:08.2 core:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:05.8 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:05.3 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:05.0 core:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.4 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:04.2 core:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:03.6 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:03.3 core:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:02.8 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:02.4 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.2 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.2 ide-haskell:check-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:01.2 ide-haskell:lint-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {},
  "haskell-ghc-mod": {
    "ghcModiPath": "/Users/ageorges/Library/Haskell/bin/ghc-modi",
    "ghcModPath": "/Users/ageorges/Library/Haskell/bin/ghc-mod"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.2
haskell-ghc-mod, v0.4.3
ide-haskell, v0.3.6
language-haskell, v1.0.0
vim-mode, v0.39.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Duplicate of #4.

**Comment by lierdakil** [comment]
Please see https://github.com/kazu-yamamoto/ghc-mod/wiki/InconsistentCabalVersions

**Comment by itkovian** [comment]
All right, closing. Thx.
