### ISSUE TITLE
Uncaught Error: Error: Command failed: c:\Users\kot\AppData\Roaming\cabal\bin\ghc-mod.exe check C:\Users\kot\AppData\Local\Temp\haskell-ghc-mod11534-15332-1ebx1yi.hsD:\git\Haskell1\Haskell1.cabal: 60: user error (Parse of field 'build-depends' failed.)

### ISSUE THREAD

**Issue by vasily-kirichenko** [lierdakil/haskell-ghc-mod#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Unknown Windows Version
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.4.3

### Stack Trace

Uncaught Error: Error: Command failed: c:\Users\kot\AppData\Roaming\cabal\bin\ghc-mod.exe check C:\Users\kot\AppData\Local\Temp\haskell-ghc-mod11534-15332-1ebx1yi.hs
D:\git\Haskell1\Haskell1.cabal: 60: user error (Parse of field 'build-depends' failed.)

```
At C:\Users\kot\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:70

Error: Error: Command failed: c:\Users\kot\AppData\Roaming\cabal\bin\ghc-mod.exe check C:\Users\kot\AppData\Local\Temp\haskell-ghc-mod11534-15332-1ebx1yi.hs
D:\git\Haskell1\Haskell1.cabal: 60: user error (Parse of field 'build-depends' failed.)

  at C:\Users\kot\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:70:17
  at ChildProcess.exithandler (child_process.js:736:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1070:5)

```

### Commands

```
     -0:17.4 snippets:next-tab-stop (atom-text-editor.editor)
     -0:17.4 snippets:expand (atom-text-editor.editor)
     -0:17.4 editor:indent (atom-text-editor.editor)
     -0:17.2 snippets:next-tab-stop (atom-text-editor.editor)
     -0:17.2 snippets:expand (atom-text-editor.editor)
     -0:17.2 editor:indent (atom-text-editor.editor)
     -0:17.0 snippets:next-tab-stop (atom-text-editor.editor)
     -0:17.0 snippets:expand (atom-text-editor.editor)
     -0:17.0 editor:indent (atom-text-editor.editor)
     -0:16.8 snippets:next-tab-stop (atom-text-editor.editor)
     -0:16.8 snippets:expand (atom-text-editor.editor)
     -0:16.8 editor:indent (atom-text-editor.editor)
     -0:16.2 core:backspace (atom-text-editor.editor)
  2x -0:13.4 core:save (atom-text-editor.editor)
     -0:09.3 ide-haskell:check-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:09.3 ide-haskell:lint-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "haskell-ghc-mod": {
    "ghcModPath": "c:\\Users\\kot\\AppData\\Roaming\\cabal\\bin\\ghc-mod.exe",
    "ghcModiPath": "c:\\Users\\kot\\AppData\\Roaming\\cabal\\bin\\ghc-modi.exe"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.8.0
git-projects, v1.13.0
haskell-ghc-mod, v0.4.3
ide-haskell, v0.3.6
language-haskell, v1.0.0
language-rust, v0.4.2
linter, v0.12.0
linter-rust, v0.0.8
racer, v0.9.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Looks like your cabal project is misconfigured. Could you check if you can
run `ghc-mod check Main.hs` (or any other existing source file) from
project directory?

Note that since you run ide-haskell anyway, it might be a good idea to
uncheck most ticks in haskell-ghc-mod settings, since ide-haskell handles
most of work by itself now. I will be consolidating these projects moving
forward, but not for a while yet.

2015-04-04 17:26 GMT+03:00 Vasily Kirichenko <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
You are right, it was a typo in the cabal file. Thanks! 
Great package, BTW :)
